### ISSUE TITLE
CRASH: Application error: a client-side exception has occurred.

### ISSUE THREAD

**Issue by ynvtlmr** [Vero-Ventures/dynamic-needs-analysis#242] opened 2024-07-26 21:44 UTC
Not really sure what is causing this crash. Might be a bad connection.

<img width="869" alt="image" src="https://github.com/user-attachments/assets/f9b24d60-c1c6-4140-ade8-dd9fe6cd01f1">

<img width="743" alt="image" src="https://github.com/user-attachments/assets/ff942ce5-5ec4-4a24-a010-db05b175ea9c">

**Comment by michaeleii** [comment] 2024-07-26 21:45
Duplicate of #236

**Closed** 2024-07-26 21:45 UTC
